### ISSUE TITLE
How to test handle_info/2 in Phoenix LiveView

### ISSUE THREAD

**Issue by nelsonic** [dwyl/email#26]
The email dashboard #23 _works_: https://phemail.herokuapp.com
![image](https://user-images.githubusercontent.com/194400/77227772-8c2a8380-6b7a-11ea-8ff5-951d986e4131.png)

But sadly we don't have a _test_ for the `handle_event/3` function: 
https://codecov.io/gh/dwyl/email/src/e19ac570bedbcb78720bae60e9215d6a8b449473/lib/app_web/live/dashboard.ex#L13
![image](https://user-images.githubusercontent.com/194400/77227810-c7c54d80-6b7a-11ea-92de-af43a3da5a63.png)

Until we figure out how to test the `handle_event/3` function we cannot reach 100% ... [![codecov.io](https://img.shields.io/codecov/c/github/dwyl/email/master.svg?style=flat-square)](http://codecov.io/github/dwyl/email?branch=master)

I've tried hacking on it for a couple of pomodoros in: [`/test/app_web/live/dashboard_test.exs`](https://github.com/dwyl/email/blob/e19ac570bedbcb78720bae60e9215d6a8b449473/test/app_web/live/dashboard_test.exs)
and read the docs: https://hexdocs.pm/phoenix_live_view/Phoenix.LiveViewTest.html#content 👀 
Stumped on how to test this ... 🤦‍♂ 

If you know how to test this please help by commenting below!

**Comment by nelsonic** [comment]
This looks promising: https://hexdocs.pm/phoenix_live_view/Phoenix.LiveViewTest.html#module-testing-events 👀

**Comment by nelsonic** [comment]
Got the error:
```
** (UndefinedFunctionError) function Floki.parse_document/1 is undefined (module Floki is not available)
```
According to: https://hexdocs.pm/phoenix_live_view/installation.html [`floki`](https://hex.pm/packages/floki) is required to test `LiveView` ...
![floki-test-dep](https://user-images.githubusercontent.com/194400/77255491-d9345580-6c5f-11ea-8568-008a00c82287.png)


So adding it to `mix.exs`:
```
{:floki, ">= 0.0.0", only: :test}
```

**Comment by nelsonic** [comment]
Continue: https://stackoverflow.com/questions/ask

How to test handle_event/3 in Phoenix LiveView

Greetings Phoenix LiveView Wizards!

I have a basic LiveView app that renders/updates a table: https://github.com/dwyl/email <br />
The code is very simple: [`lib/app_web/live/dashboard.ex`](https://github.com/dwyl/email/blob/4d20c77a70578d51370ce81d99e8f4a5d0cf449f/lib/app_web/live/dashboard.ex#L12-L16)

```elixir
defmodule AppWeb.Dashboard do
  use Phoenix.LiveView
  @topic "live"

  def mount(_session, _params, socket) do
    AppWeb.Endpoint.subscribe(@topic) # subscribe to the channel
    sent = App.Ctx.list_sent_with_status()
    {:ok, assign(socket, %{val: 0, sent: sent}),
      layout: {AppWeb.LayoutView, "live.html"}}
  end

  def handle_event("sent", _value, socket) do
    new_state = update(socket, :sent, App.Ctx.list_sent_with_status())
    AppWeb.Endpoint.broadcast_from(self(), @topic, "sent", new_state.assigns)
    {:noreply, new_state}
  end

  def handle_info(_msg, socket) do
    {:noreply, assign(socket, sent: App.Ctx.list_sent_with_status())}
  end

  def render(assigns) do
    AppWeb.PageView.render("dashboard.html", assigns)
  end
end
```
The code works as expected, see: https://phemail.herokuapp.com <br />
but we have no idea how to _test_ the `handle_event/3` function. 🤷‍♂<br />
We have tried invoking it but we just get errors ...

**Comment by nelsonic** [comment]
Opened question on SO: https://stackoverflow.com/questions/60848600/how-to-test-handle-event-3
Also on ElixirForum: https://elixirforum.com/t/how-to-test-handle-event-3-in-phoenix-liveview/30070

Let's see what the internet says. 🙏 ⏳

**Comment by nelsonic** [comment]
Got a couple of replies on the questions. 🎉 

Progress:
![counter-not-covered](https://user-images.githubusercontent.com/194400/77537879-b8097a00-6e96-11ea-9417-7be71daee697.png)

**Comment by nelsonic** [comment]
Success! 
https://codecov.io/gh/dwyl/phoenix-liveview-counter-tutorial/src/master/lib/live_view_counter_web/live/counter.ex
![image](https://user-images.githubusercontent.com/194400/77556557-974e1e00-6eb0-11ea-9255-a0f5863f332e.png)

**Comment by nelsonic** [comment]
Now I "_just_" need to figure out how to apply this to our `dashboard.ex` ... 💭

**Comment by nelsonic** [comment]
When I attempt to run the following test using the `render_click/2` function:
```elixir
test "handle_event/3", %{conn: conn} do
  {:ok, view, html} = live(conn, "/")
  # IO.inspect(view, label: "view")
  assert view.module == AppWeb.Dashboard
  assert html =~ "Email"
  result = render_click(view, :refresh)
  IO.inspect(result, label: "result")
end
```
It gives the following error:
```
15:59:28.896 [error] GenServer #PID<0.487.0> terminating
** (BadFunctionError) expected a function, got: []
    (phoenix_live_view 0.10.0) lib/phoenix_live_view.ex:1503: Phoenix.LiveView.update/3
    (app 1.0.0) lib/app_web/live/dashboard.ex:13: AppWeb.Dashboard.handle_event/3
    (phoenix_live_view 0.10.0) lib/phoenix_live_view/channel.ex:92: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 3.11.2) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib 3.11.2) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib 3.11.2) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{event: "event", join_ref: 0, payload: %{"event" => "refresh", "type" => "click", "value" => %{}}, ref: "1", topic: "phx-Ff-XUTOFPPgWfAIj"}
```

**Comment by nelsonic** [comment]
What if I just ***`DELETE`*** the `handle_event/3` function...? 💭

**Comment by nelsonic** [comment]
Deleted the `handle_event/3` function in https://github.com/dwyl/email/commit/2a5332328a8a25d1f8cdc74b7509865b93af8fd3 and the dashboard still works https://dwylmail.herokuapp.com 
and we have 100% coverage! https://codecov.io/github/dwyl/email?branch=master
