### ISSUE TITLE
ExAws: HTTP ERROR: :nxdomain

### ISSUE THREAD

**Issue by nelsonic** [dwyl/email#31]
Sending emails was working fine last week, but today I'm getting an AWS warning:
```
10:32:59.558 request_id=FgFZtWxSl7ACMQkAAAPG [warn] ExAws: HTTP ERROR: :nxdomain for URL: "https://lambda.eu-west-1.amazonaws.com/2015-03-31/functions/aws-ses-lambda-v1/invocations" ATTEMPT: 1
10:32:59.581 request_id=FgFZtWxSl7ACMQkAAAPG [warn] ExAws: HTTP ERROR: :nxdomain for URL: "https://lambda.eu-west-1.amazonaws.com/2015-03-31/functions/aws-ses-lambda-v1/invocations" ATTEMPT: 2
10:32:59.608 request_id=FgFZtWxSl7ACMQkAAAPG [warn] ExAws: HTTP ERROR: :nxdomain for URL: "https://lambda.eu-west-1.amazonaws.com/2015-03-31/functions/aws-ses-lambda-v1/invocations" ATTEMPT: 3
10:32:59.629 request_id=FgFZtWxSl7ACMQkAAAPG [warn] ExAws: HTTP ERROR: :nxdomain for URL: "https://lambda.eu-west-1.amazonaws.com/2015-03-31/functions/aws-ses-lambda-v1/invocations" ATTEMPT: 4
10:32:59.790 request_id=FgFZtWxSl7ACMQkAAAPG [warn] ExAws: HTTP ERROR: :nxdomain for URL: "https://lambda.eu-west-1.amazonaws.com/2015-03-31/functions/aws-ses-lambda-v1/invocations" ATTEMPT: 5
10:32:59.980 request_id=FgFZtWxSl7ACMQkAAAPG [warn] ExAws: HTTP ERROR: :nxdomain for URL: "https://lambda.eu-west-1.amazonaws.com/2015-03-31/functions/aws-ses-lambda-v1/invocations" ATTEMPT: 6
10:33:00.108 request_id=FgFZtWxSl7ACMQkAAAPG [warn] ExAws: HTTP ERROR: :nxdomain for URL: "https://lambda.eu-west-1.amazonaws.com/2015-03-31/functions/aws-ses-lambda-v1/invocations" ATTEMPT: 7
10:33:00.897 request_id=FgFZtWxSl7ACMQkAAAPG [warn] ExAws: HTTP ERROR: :nxdomain for URL: "https://lambda.eu-west-1.amazonaws.com/2015-03-31/functions/aws-ses-lambda-v1/invocations" ATTEMPT: 8
10:33:00.979 request_id=FgFZtWxSl7ACMQkAAAPG [warn] ExAws: HTTP ERROR: :nxdomain for URL: "https://lambda.eu-west-1.amazonaws.com/2015-03-31/functions/aws-ses-lambda-v1/invocations" ATTEMPT: 9
10:33:01.351 request_id=FgFZtWxSl7ACMQkAAAPG [warn] ExAws: HTTP ERROR: :nxdomain for URL: "https://lambda.eu-west-1.amazonaws.com/2015-03-31/functions/aws-ses-lambda-v1/invocations" ATTEMPT: 10
```

investigating ...

**Comment by nelsonic** [comment]
A bit more detail when running the lambda function on `localhost`:
```
err: UnknownEndpoint: Inaccessible host: `email.eu-west-1.amazonaws.com'. This service may not be available in the `eu-west-1' region.
    at Request.ENOTFOUND_ERROR (/Users/n/code/aws-ses-lambda/node_modules/aws-sdk/lib/event_listeners.js:495:46)
    at Request.callListeners (/Users/n/code/aws-ses-lambda/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/n/code/aws-ses-lambda/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/n/code/aws-ses-lambda/node_modules/aws-sdk/lib/request.js:683:14)
    at ClientRequest.error (/Users/n/code/aws-ses-lambda/node_modules/aws-sdk/lib/event_listeners.js:333:22)
    at ClientRequest.<anonymous> (/Users/n/code/aws-ses-lambda/node_modules/aws-sdk/lib/http/node.js:96:19)
    at ClientRequest.emit (events.js:223:5)
    at ClientRequest.EventEmitter.emit (domain.js:475:20)
    at TLSSocket.socketErrorListener (_http_client.js:415:9)
    at TLSSocket.emit (events.js:223:5) {
  message: "Inaccessible host: `email.eu-west-1.amazonaws.com'. This service may not be available in the `eu-west-1' region.",
  code: 'UnknownEndpoint',
  region: 'eu-west-1',
  hostname: 'email.eu-west-1.amazonaws.com',
  retryable: true,
  originalError: Error: getaddrinfo ENOTFOUND email.eu-west-1.amazonaws.com
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
    message: 'getaddrinfo ENOTFOUND email.eu-west-1.amazonaws.com',
    errno: 'ENOTFOUND',
    code: 'NetworkingError',
    syscall: 'getaddrinfo',
    hostname: 'email.eu-west-1.amazonaws.com',
    region: 'eu-west-1',
    retryable: true,
    time: 2020-03-31T11:55:17.835Z
  },
  time: 2020-03-31T11:55:17.835Z
}
```

**Comment by nelsonic** [comment]
Similar to: https://github.com/aws/aws-sdk-js/issues/2618
Going to attempt to upgrade the SDK ...

**Comment by nelsonic** [comment]
From the Heroku Logs:
```
2020-03-31T14:13:23.438817+00:00 app[web.1]: Request: POST /api/sns
2020-03-31T14:13:23.438818+00:00 app[web.1]: ** (exit) an exception was raised:
2020-03-31T14:13:23.438818+00:00 app[web.1]:     ** (FunctionClauseError) no function clause matching in App.Ctx.update_sent/2
2020-03-31T14:13:23.438821+00:00 app[web.1]:         (app 1.0.0) lib/app/ctx.ex:99: App.Ctx.update_sent(nil, %{aud: "Joken", email: "success@simulator.amazonses.com", exp: 1585671199, iat: 1585663999, id: 167, iss: "Joken", jti: "2o0mi0dp03uvgva6f00000r1", message_id: "0102017130f08aab-55d548dd-e303-44b8-b0fc-53cba15f0438-000000", name: "Super Successful /api/send test", nbf: 1585663999, request_id: "e6dbdfe9-96a9-4f8a-855a-2c8b17c8466b", status: "Sent", status_id: 3, template: "welcome"})
2020-03-31T14:13:23.438821+00:00 app[web.1]:         (app 1.0.0) lib/app/ctx.ex:177: App.Ctx.upsert_sent/1
2020-03-31T14:13:23.438822+00:00 app[web.1]:         (app 1.0.0) lib/app_web/controllers/sent_controller.ex:98: AppWeb.SentController.process_sns/2
2020-03-31T14:13:23.438822+00:00 app[web.1]:         (app 1.0.0) lib/app_web/controllers/sent_controller.ex:1: AppWeb.SentController.action/2
2020-03-31T14:13:23.438822+00:00 app[web.1]:         (app 1.0.0) lib/app_web/controllers/sent_controller.ex:1: AppWeb.SentController.phoenix_controller_pipeline/2
2020-03-31T14:13:23.438823+00:00 app[web.1]:         (phoenix 1.4.16) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
2020-03-31T14:13:23.438823+00:00 app[web.1]:         (app 1.0.0) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.plug_builder_call/2
2020-03-31T14:13:23.438823+00:00 app[web.1]:         (app 1.0.0) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.call/2
```

**Comment by nelsonic** [comment]
need so use `is_nil/1` to check if `claims.id` is set:
```
2020-03-31T15:20:39.151778+00:00 app[web.1]: 15:20:39.151 request_id=8e18bd61-4a86-467a-a064-92867b7a5148 [info] Sent 500 in 580ms
2020-03-31T15:20:39.151928+00:00 app[web.1]: 15:20:39.151 request_id=8e18bd61-4a86-467a-a064-92867b7a5148 [info] Converted error ArgumentError to 500 response
2020-03-31T15:20:39.167095+00:00 app[web.1]: 15:20:39.166 [error] #PID<0.571.0> running AppWeb.Endpoint (connection #PID<0.570.0>, stream id 1) terminated
2020-03-31T15:20:39.167097+00:00 app[web.1]: Server: dwylmail.herokuapp.com:80 (http)
2020-03-31T15:20:39.167098+00:00 app[web.1]: Request: POST /api/sns
2020-03-31T15:20:39.167098+00:00 app[web.1]: ** (exit) an exception was raised:
2020-03-31T15:20:39.167106+00:00 app[web.1]:     ** (ArgumentError) nil given for :id. Comparison with nil is forbidden as it is unsafe. Instead write a query with is_nil/1, for example: is_nil(s.id)
2020-03-31T15:20:39.167113+00:00 app[web.1]:         (ecto 3.3.4) lib/ecto/query/builder/filter.ex:129: Ecto.Query.Builder.Filter.kw!/7
2020-03-31T15:20:39.167113+00:00 app[web.1]:         (ecto 3.3.4) lib/ecto/query/builder/filter.ex:122: Ecto.Query.Builder.Filter.kw!/3
2020-03-31T15:20:39.167114+00:00 app[web.1]:         (ecto 3.3.4) lib/ecto/query/builder/filter.ex:104: Ecto.Query.Builder.Filter.filter!/6
2020-03-31T15:20:39.167114+00:00 app[web.1]:         (ecto 3.3.4) lib/ecto/query/builder/filter.ex:116: Ecto.Query.Builder.Filter.filter!/7
2020-03-31T15:20:39.167114+00:00 app[web.1]:         (ecto 3.3.4) lib/ecto/repo/queryable.ex:70: Ecto.Repo.Queryable.get_by/4
2020-03-31T15:20:39.167116+00:00 app[web.1]:         (app 1.0.0) lib/app/ctx.ex:175: App.Ctx.upsert_sent/1
2020-03-31T15:20:39.167116+00:00 app[web.1]:         (app 1.0.0) lib/app_web/controllers/sent_controller.ex:103: AppWeb.SentController.process_sns/2
2020-03-31T15:20:39.167116+00:00 app[web.1]:         (app 1.0.0) lib/app_web/controllers/sent_controller.ex:1: AppWeb.SentController.action/2
```

**Comment by nelsonic** [comment]
`<AccessDeniedException>`: https://travis-ci.org/github/dwyl/email/builds/669296264#L566
```
1) test /api/send send an email via /api/send (AppWeb.SentControllerTest)
     test/app_web/controllers/sent_controller_test.exs:134
     ** (MatchError) no match of right hand side value: {:error, {:http_error, 403, %{body: "<AccessDeniedException>\n  <Message>Unable to determine service/operation name to be authorized</Message>\n</AccessDeniedException>\n", headers: [{"Date", "Tue, 31 Mar 2020 15:37:13 GMT"}, {"Content-Length", "130"}, {"Connection", "keep-alive"}, {"x-amzn-RequestId", "11142243-45ee-4c6c-b1e2-ce0a526cc8bc"}], status_code: 403}}}
     code: |> post("/api/send")
     stacktrace:
       (app 1.0.0) lib/app_web/controllers/sent_controller.ex:34: AppWeb.SentController.send_email/1
       (app 1.0.0) lib/app_web/controllers/sent_controller.ex:48: AppWeb.SentController.send_email_check_auth_header/2
       (app 1.0.0) lib/app_web/controllers/sent_controller.ex:1: AppWeb.SentController.action/2
       (app 1.0.0) lib/app_web/controllers/sent_controller.ex:1: AppWeb.SentController.phoenix_controller_pipeline/2
       (phoenix 1.4.16) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
       (app 1.0.0) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.plug_builder_call/2
       (app 1.0.0) lib/app_web/endpoint.ex:1: AppWeb.Endpoint.call/2
       (phoenix 1.4.16) lib/phoenix/test/conn_test.ex:235: Phoenix.ConnTest.dispatch/5
       test/app_web/controllers/sent_controller_test.exs:144: (test)
```

Sadly, this StackOverflow post: https://stackoverflow.com/questions/41371970/accessdeniedexception-unable-to-determine-service-operation-name-to-be-authoriz which seems relevant but we don't have control over the HTTP method in `ExAws`. 🤷‍♂

**Comment by nelsonic** [comment]
# [PEBKAC](https://en.wikipedia.org/wiki/User_error#PEBKAC) ... 🤦‍♂ 

I forgot to add `export AWS_LAMBDA_FUNCTION=aws-ses-lambda-v1` to Travis-CI and Heroku ... 😧 
I _eventually_ figured it out but this should never have been an issue!
